### ISSUE TITLE
RuntimeError: No points provided

### ISSUE THREAD

**Issue by grannycola** [motern88/Det-SAM2#3]
I am trying to run the det_sam2_RT.py script with the following code:

``` python
if __name__ == '__main__':
    sam2_output_frame_dir = './temp_output/video_frames'
    sam2_checkpoint_path = '../checkpoints/sam2.1_hiera_base_plus.pt'
    sam2_config_path = './configs/sam2.1/sam2.1_hiera_b+.yaml'
    detect_model_weights = '/app/det_weights/train_referee12_960.pt'
    output_video_dir = './pipeline_output'
    video_path = '/app/det_sam2_inference/example/crowd.mp4'
    save_inference_state_path = '/app/autodl-tmp/output_inference_state/inference_state_10frames.pkl'
    processor = VideoProcessor(
        output_dir=output_video_dir,
        sam2_checkpoint=sam2_checkpoint_path,
        model_cfg=sam2_config_path,
        detect_model_weights=detect_model_weights,
    )
    processor.run(
        video_path=video_path,
    )
```
Do I understand correctly that it should be self-prompted and I don't need to specify the points? However, I encounter the following error:
```
---最大累积帧数/frame_buffer_size:30,检测间隔/detect_interval:30,最大传播长度/max_frame_num_to_track:60,推理保留帧数/max_inference_state_frames:60,预加载内存库/load_inference_state_path:None,
Initializing: offload_video_to_cpu:True,offload_state_to_cpu:False
Traceback (most recent call last):
  File "/app/det_sam2_inference/det_sam2_runtime.py", line 715, in <module>
    processor.run(
  File "/app/det_sam2_inference/det_sam2_runtime.py", line 611, in run
    self.inference_state = self.process_frame(self.pre_frames + frame_idx, frame_rgb)
  File "/app/det_sam2_inference/det_sam2_runtime.py", line 441, in process_frame
    self.Detect_and_SAM2_inference(frame_idx)
  File "/app/det_sam2_inference/det_sam2_runtime.py", line 394, in Detect_and_SAM2_inference
    for out_frame_idx, out_obj_ids, out_mask_logits in self.predictor.propagate_in_video(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/app/sam2/sam2_video_predictor.py", line 1119, in propagate_in_video
    raise RuntimeError("No points provided; please add points first / 没有提供点；请先添加点")
RuntimeError: No points provided; please add points first / 没有提供点；请先添加点
```
What could be the cause of the error?

**Comment by GoldenFishes** [comment]
Make sure that the first frame in the video is a conditional frame—that is, the first frame in the video can be detected by the detection model.
For example, if you use the detection model I provided (in the billiards scenario), then the video should contain any billiard object at the beginning for SAM2 to reason properly.
You can uncomment in the `det_sam2_RT.py` `VideoProcessor.detect_predict()` function:

`print(f"Frame index (excluding pre-loaded): {absolute_indices[i]-self.pre_frames}: Coordinates: {coords}, Class: {cls}, Confidence: {conf}")`
to confirm that the detection model captured any objects in the first frame

**Comment by grannycola** [comment]
Am I correct in understanding that your model does not perform online tracking since the number of object IDs is limited by the number of classes (as in your case, where each ball has its own class)? In other words, there is no mechanism for assigning new IDs (as in a classic online tracker), correct?

**Comment by GoldenFishes** [comment]
Yes. Detection model detects categories, from the category concept to the gap of the object concept of SAM2 I can't think of any good way to solve it.

**Comment by GoldenFishes** [comment]
So, another point to be aware of is to make sure that only one object appears in each category detected by the detection model.

The detection model in Det-SAM2 wants to play a role in prompting correction, so when two identical detection categories appear at the same time, the detection model cannot tell the correspondence of objects in the same category before and after SAM2

**Comment by GoldenFishes** [comment]
We can't easily assign IDs to the same categories of detection models. Because we need to make sure that the prompt input of SAM2 is absolutely correct.
